#!/usr/bin/python3

import os
import sys
from subprocess import call

if len(sys.argv) < 2:
    print('Input file missing')
    exit(3)

input_file = sys.argv[1]

output_file = input_file
if output_file[-3:] == '.md':
    output_file = output_file[:-3]

title = output_file
output_file = output_file + '.html'

cli_cmd = [
    '/usr/bin/pandoc',
    input_file,
    '--output=' + output_file,
    '--to=html5',
    f'--css={os.getenv("HOME")}/.local/share/markdown-css/github.css',
    '--highlight-style=haddock',
    '--self-contained',
    '--metadata',
    f'pagetitle="{title}"'
]
call(cli_cmd)
